# Generated by Django 4.0.5 on 2023-10-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20230810_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborgs',
            name='org_code',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True, verbose_name='Байгууллагын код'),
        ),
    ]
